### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by daviddgn** [stbaer/rangeslider-js#11]
I tried the examples on http://stbaer.github.io/rangeslider-js/#/examples and had tested it with chrome mobile inspector console. This was the output on loading the page:

> (index):3 Uncaught TypeError: rangesliderJs.create is not a function
    at (index):3
(anonymous) @ (index):3
(index):3 Uncaught TypeError: rangesliderJs.create is not a function
    at (index):3
(anonymous) @ (index):3
(index):3 Uncaught TypeError: rangesliderJs.create is not a function
    at (index):3
(anonymous) @ (index):3
(index):5 Uncaught TypeError: rangesliderJs.create is not a function
    at (index):5

The input:ranges was not being created successfully. Then I tried this:

> temp1
<input id=​"slider" type=​"range" min=​"0" max=​"5" value=​"1" step=​"1">​

`rangesliderJs.default.create(temp1)`

And the result was that the input was converted with rangeslider correctly. But then I saw that the problem I found in my own project was happening also in the examples. On moving the range, this appeared on console:

> rangeslider-js.min.js:1 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

**Comment by stbaer** [comment]
Hi @daviddgn - it should be fixed with the latest release.
