### ISSUE TITLE
Custom css classes?

### ISSUE THREAD

**Issue by adamsoffer** [stbaer/rangeslider-js#4]
The original library lets you override default classes:
```
{
    rangeClass: 'rangeslider',
    disabledClass: 'rangeslider--disabled',
    horizontalClass: 'rangeslider--horizontal',
    verticalClass: 'rangeslider--vertical',
    fillClass: 'rangeslider__fill',
    handleClass: 'rangeslider__handle'
}
```

**Comment by stbaer** [comment]
Hi @adamsoffer - sorry for the late reply, somehow missed this issue. 

It's possible, but I don't see a big benefit in it and would like to keep this small. If theres a real use case for custom classes I would prefer giving the option to add additional classnames instead of overriding.
